---
title: "modelling 4"
author: "u1814083"
date: "01/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(dplyr)
CovidData <- read.csv("tidycovid19.csv")

library(lubridate)
CovidData$date = as.Date(parse_date_time(CovidData$date,orders=c("y","ym","ymd")))

firstDiff <- function(x) {
  shifted <- c(0,x[1:(length(x)-1)])
  result = x-shifted
  which_negative = which(result<0)
  result[which_negative] = NA
  return(result)
}
CovidData <- CovidData %>%
  mutate(daily_confirmed = firstDiff(confirmed))
CovidData <- CovidData %>%
  mutate(daily_deaths = firstDiff(deaths))
CovidData <- CovidData %>%
  mutate(daily_recovered = firstDiff(recovered))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# select countries
targeted_countries <- c("United Kingdom", "Sweden", "Italy", "Brazil","Canada","United States")

EUAdata <- CovidData %>% filter(country %in% targeted_countries, 
                                (date > as.Date("2020-02-06")))
```

# General pattern

```{r, fig.height= 8, fig.width=10, echo = FALSE, message = FALSE, warning=FALSE}

plot_ContinentalConfirmed <- ggplot(EUAdata, aes(x=date, y=log(daily_confirmed), col=country)) + geom_point(size=.75) + labs(title = "Confirmed Cases against time")

#plot_ContinentalConfirmed2 <- ggplot(EUAdata, aes(x=date, y=confirmed, col=country)) + geom_point(size=1) + labs(title = "Confirmed Cases against time")

plot_gcmr_retail_recreation <- ggplot(EUAdata, aes(x=date, y=gcmr_retail_recreation, col=country)) + geom_point(size=.75) + labs(title = "gcmr_retail_recreation")

plot_gcmr_workplaces <- ggplot(EUAdata, aes(x=date, y=gcmr_workplaces, col=country)) + geom_point(size=.75) + labs(title = "gcmr_workplaces")

plot_gcmr_grocery_pharmacy<- ggplot(EUAdata, aes(x=date, y=gcmr_grocery_pharmacy, col=country)) + geom_point(size=.75) + labs(title = "gcmr_grocery_pharmacy")

library("gridExtra")
grid.arrange(plot_ContinentalConfirmed,plot_gcmr_retail_recreation, plot_gcmr_workplaces,plot_gcmr_grocery_pharmacy, ncol=2, top="Variable comparation")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

# First wave plots

```{r, fig.height=6,fig.width=10,echo=TRUE, warning=FALSE, message=FALSE}
print(targeted_countries)
wave_dates <- c("2020-07-15", "2020-07-20", "2020-07-01", "2020-11-01", "2020-08-10", "2020-06-07")
print(wave_dates)
```


```{r, fig.height=6,fig.width=10,echo=TRUE, warning=FALSE, message=FALSE}
library(splines)

library(splines)

# a function that fits with gcmr data with respect to variable names
plot_gcmr_wave3 <- function(y="gcmr_retail_recreation"){
  
  # a function for plotting each country
  plot_country1 <- function(country_name="", date_range = c("2020-02-06", "2020-07-15")){
    selected <- EUAdata %>% 
      filter(country == country_name)
    
    
    # to eliminate "double curves", we omit weekends data for gcmr_workplaces and gcmr_grocery_pharmacy
    if (y == "gcmr_workplaces" | y == "gcmr_grocery_pharmacy"){
      selected <- selected %>% filter(!(weekdays(as.Date(date)) %in% c('Saturday','Sunday')))
    }
    selected <- selected %>% filter(!is.na(selected[,y]),
           (date > as.Date(date_range[1])) & (date < as.Date(date_range[2]))) %>%
      mutate(date = yday(date))
    
    
    if(i==6){
      print(as.Date(selected$date, "2020-01-01"))
    }
    glm_fit <- glm(selected[,y] ~  1 + ns(date, knots = c(60,100,140,180))
                   # + I(date^3) + I(date^4) + I(date^5)
                   ,data = selected)
    #glm_fit <- glm(selected[,y] ~ date, data = selected)
    predict.1 <- predict(glm_fit)
    
    plot_0 <- ggplot(aes(x = as.Date(date,origin = "2020-01-01"), y = selected[,y]), data = selected) +
      geom_point(size=1) +
      geom_line(y=predict.1, color="red") + 
      labs(x = "Dates", y = "% change from baseline",
        title = country_name)
    
    #print(coef(glm_fit))
    return(plot_0)
  }

  myplots <- vector('list', 6)
  for(i in 1:length(targeted_countries)){
    
    #append(l,plot_country1(country))
    myplots[[i]] <- plot_country1(targeted_countries[i])
  }
  
  
  #return(myplots)
  
  multiplot(plotlist = myplots, cols = 2)
}
#"2020-07-15" "2020-07-20" "2020-07-01" "2020-11-01" "2020-08-10"
#[6] "2020-06-07"
plot_gcmr_wave3("gcmr_retail_recreation")
#print(as.Date(wave_dates[1]))
```

```{r, fig.height=6,fig.width=10,echo=TRUE, warning=FALSE, message=FALSE}
plot_gcmr_wave1("gcmr_workplaces")
```

```{r, fig.height=6,fig.width=10,echo=TRUE, warning=FALSE, message=FALSE}
#plot_gcmr("gcmr_grocery_pharmacy")
```

# Second wave plots

```{r, fig.height=6,fig.width=10,echo=FALSE, warning=FALSE, message=FALSE}
library(splines)

# a function that fits with gcmr data with respect to variable names
plot_gcmr_wave2 <- function(y="gcmr_retail_recreation"){
  
  # a function for plotting each country
  plot_country1 <- function(country_name="", date_range = c("2020-02-06", "2020-07-15")){
    selected <- EUAdata %>% 
      filter(country == country_name)
    
    # to eliminate "double curves", we omit weekends data for gcmr_workplaces and gcmr_grocery_pharmacy
    if (y == "gcmr_workplaces" | y == "gcmr_grocery_pharmacy"){
      selected <- selected %>% filter(!(weekdays(as.Date(date)) %in% c('Saturday','Sunday')))
    }
    selected <- selected %>% filter(!is.na(selected[,y]),
           (date > as.Date(date_range[1])) & (date < as.Date(date_range[2]))) %>%
      mutate(date = yday(date))
    
    
    glm_fit <- glm(selected[,y] ~  1 + ns(date, knots = c(60,100,140,180))
                   # + I(date^3) + I(date^4) + I(date^5)
                   ,data = selected)
    #glm_fit <- glm(selected[,y] ~ date, data = selected)
    predict.1 <- predict(glm_fit)

    plot_0 <- ggplot(aes(x = as.Date(date,origin = "2020-01-01"), y = selected[,y]), data = selected) +
      geom_point(size=1) +
      geom_line(y=predict.1, color="red") + 
      labs(x = "Dates", y = "% change from baseline",
        title = country_name)
    #print(coef(glm_fit))
    return(plot_0)
  }

  myplots <- vector('list', 6)
  for(i in 1:length(targeted_countries)){
    #append(l,plot_country1(country))
    myplots[[i]] <- plot_country1(targeted_countries[i], date_range = c(wave_dates[i], "2020-12-15"))
  }
  #return(myplots)
  multiplot(plotlist = myplots, cols = 2)
}

plot_gcmr_wave2("gcmr_retail_recreation")


```
```{r, fig.height=6,fig.width=10,echo=FALSE, warning=FALSE, message=FALSE}
plot_gcmr_wave2("gcmr_workplaces")
```

## Country comparing

```{r, echo=TRUE, warning=FALSE, message=FALSE}
library(splines)

y="gcmr_retail_recreation"
selected <- EUAdata
if (y == "gcmr_workplaces" | y == "gcmr_grocery_pharmacy"){
  selected <- selected %>% filter(!(weekdays(as.Date(date)) %in% c('Saturday','Sunday')))}
selected <- selected %>% filter(!is.na(selected[,y]),(date > as.Date("2020-02-06")) & (date < as.Date("2020-07-15"))) %>% mutate(date = yday(date))

selected <- selected %>% group_by(country)%>%ungroup()
plot_spline <- {selected %>% 
    ggplot(aes(x = as.Date(date, origin="2020-01-01"),y = gcmr_retail_recreation,col=country)) +
    geom_point()}
print(plot_spline)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
library(splines)
library(MASS)

model1 = glm(gcmr_retail_recreation ~  1 + ns(date, knots = c(60,100,140,180)),data = selected)

model2 = glm(gcmr_retail_recreation ~ country + ns(date, knots = c(60,100,140,180)), data = selected)

model3 = glm(gcmr_retail_recreation ~ -1 + country + country:ns(date, knots = c(60,100,140,180)), data = selected)
```

```{r, echo=TRUE, warning=FALSE, message=FALSE}
model1
model2
model3
```



```{r, echo=FALSE, warning=FALSE, message=FALSE}
anova(model1, model2, model3)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(splines)

y="gcmr_retail_recreation"
selected <- EUAdata
if (y == "gcmr_workplaces" | y == "gcmr_grocery_pharmacy"){
  selected <- selected %>% filter(!(weekdays(as.Date(date)) %in% c('Saturday','Sunday')))}
selected <- selected %>% filter(!is.na(selected[,y]),(date > as.Date("2020-07-16")) & (date < as.Date("2020-12-15"))) %>% mutate(date = yday(date))

selected <- selected %>% group_by(country)%>%ungroup()
plot_spline <- {selected %>% 
    ggplot(aes(x = as.Date(date, origin="2020-01-01"),y = gcmr_retail_recreation,col=country)) +
    geom_point()}
print(plot_spline)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(splines)
library(MASS)

model1 = glm(gcmr_retail_recreation ~  1 + ns(date, knots = c(60,100,140,180)),data = selected)

model2 = glm(gcmr_retail_recreation ~ country + ns(date, knots = c(60,100,140,180)), data = selected)

model3 = glm(gcmr_retail_recreation ~ -1 + country + country:ns(date, knots = c(60,100,140,180)), data = selected)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
model1
model2
model3
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

```


